[package]
name = "hello-world"
version = "0.1.0"
edition = "2018"
description = "print hello world"
repository = "https://github.com/chriamue/yocto_pi_rust_app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
